name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ronhunk-demo-python:$(date +%s)

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          registry: docker.io
          push: true
          tags: rickyraindocker/ronhunk-demo-python:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
